### ISSUE TITLE
Release on crates

### ISSUE THREAD

**Issue by werdahias** [ids1024/iso9660-rs#3]
Please release this library on crates.io,

**Comment by ids1024** [comment]
It's intentionally not on crates.io since it's a fairly incomplete work in progress implementation. I was kind of intending to release it on crates.io once it had a more complete implementation of the ISO 9660 standard, and I was fairly happy with the API, but I haven't worked on it in a while.

**Comment by werdahias** [comment]
Ok, I can understand that. Maybe you could release an alpha version? I'd need your crate to package popsicle, and the best way for it would be if it was on crates.io

**Comment by ids1024** [comment]
I guess there isn't all that high a standard for publishing on crates.io, this crate is already somewhat useful as is, and no one else has claimed the crate name for a better ISO 9660 implementation.

Published as https://crates.io/crates/iso9660.

**Comment by werdahias** [comment]
Thanks my dude.
